apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myTemplate.Variable"  . }}
  labels: {{ include "myTemplate.selectorLabel" . | nindent 4 }} 
spec:
  replicas: {{ if eq .Values.replicaFlag "1" }}5 {{ else }}2 {{ end }}
  selector:
    matchLabels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
          - name: {{ .Values.image.name }}
            image: {{ .Values.image.name }}:{{ .Values.image.tag}}
            ports:
              - containerPort: 80
            volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: {{ include "test.withFunction"  . }}
          configMap:
            name: nginx-config