apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
     app: {{ .Chart.Name }}
     release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      {{- include "myTemplate.portMap" . | nindent 6}}